In [1]:
import torch
import torch.nn as nn

In [14]:
#--define lengths
seq_length = 10
d_model=8

In [15]:
#--define even and odd indices
even_indices = torch.arange(0, d_model, 2).float()
odd_indices = torch.arange(1, d_model, 2).float()

even_indices, odd_indices

(tensor([0., 2., 4., 6.]), tensor([1., 3., 5., 7.]))

In [16]:
#--define denominator
denominator = torch.pow(10000, (even_indices / d_model)).float()
denominator

tensor([   1.,   10.,  100., 1000.])

In [17]:
#--define positions
positions = torch.arange(seq_length).float().reshape(seq_length, 1)
positions

tensor([[0.],
        [1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [18]:
pe_even = torch.sin(positions / denominator)
pe_odd = torch.cos(positions / denominator)
pe_even, pe_odd

(tensor([[ 0.0000,  0.0000,  0.0000,  0.0000],
         [ 0.8415,  0.0998,  0.0100,  0.0010],
         [ 0.9093,  0.1987,  0.0200,  0.0020],
         [ 0.1411,  0.2955,  0.0300,  0.0030],
         [-0.7568,  0.3894,  0.0400,  0.0040],
         [-0.9589,  0.4794,  0.0500,  0.0050],
         [-0.2794,  0.5646,  0.0600,  0.0060],
         [ 0.6570,  0.6442,  0.0699,  0.0070],
         [ 0.9894,  0.7174,  0.0799,  0.0080],
         [ 0.4121,  0.7833,  0.0899,  0.0090]]),
 tensor([[ 1.0000,  1.0000,  1.0000,  1.0000],
         [ 0.5403,  0.9950,  0.9999,  1.0000],
         [-0.4161,  0.9801,  0.9998,  1.0000],
         [-0.9900,  0.9553,  0.9996,  1.0000],
         [-0.6536,  0.9211,  0.9992,  1.0000],
         [ 0.2837,  0.8776,  0.9988,  1.0000],
         [ 0.9602,  0.8253,  0.9982,  1.0000],
         [ 0.7539,  0.7648,  0.9976,  1.0000],
         [-0.1455,  0.6967,  0.9968,  1.0000],
         [-0.9111,  0.6216,  0.9960,  1.0000]]))

In [19]:
pe_even.shape, pe_odd.shape

(torch.Size([10, 4]), torch.Size([10, 4]))

In [20]:
stacked=torch.stack([pe_even, pe_odd], dim=2)
stacked.shape

torch.Size([10, 4, 2])

In [21]:
stacked

tensor([[[ 0.0000e+00,  1.0000e+00],
         [ 0.0000e+00,  1.0000e+00],
         [ 0.0000e+00,  1.0000e+00],
         [ 0.0000e+00,  1.0000e+00]],

        [[ 8.4147e-01,  5.4030e-01],
         [ 9.9833e-02,  9.9500e-01],
         [ 9.9998e-03,  9.9995e-01],
         [ 1.0000e-03,  1.0000e+00]],

        [[ 9.0930e-01, -4.1615e-01],
         [ 1.9867e-01,  9.8007e-01],
         [ 1.9999e-02,  9.9980e-01],
         [ 2.0000e-03,  1.0000e+00]],

        [[ 1.4112e-01, -9.8999e-01],
         [ 2.9552e-01,  9.5534e-01],
         [ 2.9995e-02,  9.9955e-01],
         [ 3.0000e-03,  1.0000e+00]],

        [[-7.5680e-01, -6.5364e-01],
         [ 3.8942e-01,  9.2106e-01],
         [ 3.9989e-02,  9.9920e-01],
         [ 4.0000e-03,  9.9999e-01]],

        [[-9.5892e-01,  2.8366e-01],
         [ 4.7943e-01,  8.7758e-01],
         [ 4.9979e-02,  9.9875e-01],
         [ 5.0000e-03,  9.9999e-01]],

        [[-2.7942e-01,  9.6017e-01],
         [ 5.6464e-01,  8.2534e-01],
         [ 5.9964e-02,  9.

In [22]:
pe=torch.flatten(stacked, start_dim=1, end_dim=2)
pe.shape

torch.Size([10, 8])

In [23]:
pe

tensor([[ 0.0000e+00,  1.0000e+00,  0.0000e+00,  1.0000e+00,  0.0000e+00,
          1.0000e+00,  0.0000e+00,  1.0000e+00],
        [ 8.4147e-01,  5.4030e-01,  9.9833e-02,  9.9500e-01,  9.9998e-03,
          9.9995e-01,  1.0000e-03,  1.0000e+00],
        [ 9.0930e-01, -4.1615e-01,  1.9867e-01,  9.8007e-01,  1.9999e-02,
          9.9980e-01,  2.0000e-03,  1.0000e+00],
        [ 1.4112e-01, -9.8999e-01,  2.9552e-01,  9.5534e-01,  2.9995e-02,
          9.9955e-01,  3.0000e-03,  1.0000e+00],
        [-7.5680e-01, -6.5364e-01,  3.8942e-01,  9.2106e-01,  3.9989e-02,
          9.9920e-01,  4.0000e-03,  9.9999e-01],
        [-9.5892e-01,  2.8366e-01,  4.7943e-01,  8.7758e-01,  4.9979e-02,
          9.9875e-01,  5.0000e-03,  9.9999e-01],
        [-2.7942e-01,  9.6017e-01,  5.6464e-01,  8.2534e-01,  5.9964e-02,
          9.9820e-01,  6.0000e-03,  9.9998e-01],
        [ 6.5699e-01,  7.5390e-01,  6.4422e-01,  7.6484e-01,  6.9943e-02,
          9.9755e-01,  6.9999e-03,  9.9998e-01],
        [ 9.8936

In [24]:
class PositionalEncoding(nn.Module):
    def __init__(self, d_model, seq_length):
        super(PositionalEncoding, self).__init__()
        self.d_model = d_model
        self.seq_length = seq_length

    def forward(self):
        even_indices = torch.arange(0, self.d_model, 2).float()
        denominator = torch.pow(10000, (even_indices / self.d_model)).float()
        positions = torch.arange(self.seq_length).float().reshape(self.seq_length, 1)
        pe_even = torch.sin(positions / denominator)
        pe_odd = torch.cos(positions / denominator)
        stacked=torch.stack([pe_even, pe_odd], dim=2)
        pe=torch.flatten(stacked, start_dim=1, end_dim=2)
        return pe

In [25]:
pe=PositionalEncoding(d_model=8 , seq_length=10)
pe.forward()

tensor([[ 0.0000e+00,  1.0000e+00,  0.0000e+00,  1.0000e+00,  0.0000e+00,
          1.0000e+00,  0.0000e+00,  1.0000e+00],
        [ 8.4147e-01,  5.4030e-01,  9.9833e-02,  9.9500e-01,  9.9998e-03,
          9.9995e-01,  1.0000e-03,  1.0000e+00],
        [ 9.0930e-01, -4.1615e-01,  1.9867e-01,  9.8007e-01,  1.9999e-02,
          9.9980e-01,  2.0000e-03,  1.0000e+00],
        [ 1.4112e-01, -9.8999e-01,  2.9552e-01,  9.5534e-01,  2.9995e-02,
          9.9955e-01,  3.0000e-03,  1.0000e+00],
        [-7.5680e-01, -6.5364e-01,  3.8942e-01,  9.2106e-01,  3.9989e-02,
          9.9920e-01,  4.0000e-03,  9.9999e-01],
        [-9.5892e-01,  2.8366e-01,  4.7943e-01,  8.7758e-01,  4.9979e-02,
          9.9875e-01,  5.0000e-03,  9.9999e-01],
        [-2.7942e-01,  9.6017e-01,  5.6464e-01,  8.2534e-01,  5.9964e-02,
          9.9820e-01,  6.0000e-03,  9.9998e-01],
        [ 6.5699e-01,  7.5390e-01,  6.4422e-01,  7.6484e-01,  6.9943e-02,
          9.9755e-01,  6.9999e-03,  9.9998e-01],
        [ 9.8936